// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9bm45uPKe2WRWn7_K1uUprLw7pl6UMd0',
    appId: '1:365694737933:web:7d819de4cf4bfb8eff3f44',
    messagingSenderId: '365694737933',
    projectId: 'login-flutter2',
    authDomain: 'login-flutter2.firebaseapp.com',
    storageBucket: 'login-flutter2.appspot.com',
    measurementId: 'G-491MEHE60D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvu8kUphPhvICTsCmKryW4YFhrQNGkWC0',
    appId: '1:365694737933:android:aa2ace760aae1f19ff3f44',
    messagingSenderId: '365694737933',
    projectId: 'login-flutter2',
    storageBucket: 'login-flutter2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcxwgQ7c8O2u2IjyaRUq5xmQApN_yXWPU',
    appId: '1:365694737933:ios:d111f5e9dd9014aaff3f44',
    messagingSenderId: '365694737933',
    projectId: 'login-flutter2',
    storageBucket: 'login-flutter2.appspot.com',
    iosClientId: '365694737933-dh7jldb31btig9td4dbgkde7r5j22bt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcxwgQ7c8O2u2IjyaRUq5xmQApN_yXWPU',
    appId: '1:365694737933:ios:e5e207bc86a9c2f0ff3f44',
    messagingSenderId: '365694737933',
    projectId: 'login-flutter2',
    storageBucket: 'login-flutter2.appspot.com',
    iosClientId: '365694737933-31ps02m8j2s41jvk4ngkenco8vuteesc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter2.RunnerTests',
  );
}
